### ISSUE TITLE
io.sockets.clients no longer exist any more

### ISSUE THREAD

**Issue by tdjackey** [tegioz/chat#2]
meet this error  TypeError: Object #<Namespace> has no method 'clients'

can fix it by change 
var socketsInRoom = io.sockets.clients(data.room);
 to 
socket.join(data.room);
var socketsInRoom = io.sockets.adapter.rooms[data.room];

**Comment by tegioz** [comment]
Thanks @tdjackey. It looks like there are some more things broken due to changes in dependencies (this is quite old and unfortunately I haven't updated it..), so I've just fixed the dependencies versions to make it work again.
