### ISSUE TITLE
when i create room with blank  character，can not send msg..

### ISSUE THREAD

**Issue by jhrfeng** [tegioz/chat#5]
sorry, I can not write correct English。

firstly, i created 'test   ' room , and the index of simpleChat display a 'test' room.yes, i know Source Code del with `room = room.replace(" ","");` .

The question is now,  i try send like 'xxxx' msg, console print a newMessage record , but pages  display none.

**Comment by tegioz** [comment]
Hi @jhrfeng,

I've just merged a pull request #6 from @cynthia-sg that should solve the problem you mention.

Thanks.-
